projects:
  database:
    schemaPath: src/generated/database.graphql
    extensions:
      prisma: database/prisma.yml
  app:
    schemaPath: src/generated/app.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
